
import React from "react"; import {FaExternalLinkAlt,FaFileExcel,FaBook,FaGraduationCap,FaLaptopCode} from "react-icons/fa"; import pdf from "../../assets/mis.xlsx"; import "./Accessories.css";
const items=[
{icon:<FaLaptopCode/>,tag:"MOCK EXAMS",title:"NPTEL Quiz Lab",text:"Practice selected NPTEL subjects with mock exams before the real quiz. A useful last-mile revision tool.",links:[["NPTEL Quiz","https://nptelquiz.vercel.app"],["QuizMe","https://quizme-rho.vercel.app/"]],maker:"Yuvraj Singh Deora"},
{icon:<FaGraduationCap/>,tag:"COMPREHENSIVE EXAM",title:"Semester-wide practice",text:"A 100-question practice set spanning multiple semesters — useful for building recall before the comprehensive exam.",links:[["Open practice","https://quiz-me-zeta.vercel.app/"]],maker:"Yuvraj Singh Deora"},
{icon:<FaFileExcel/>,tag:"PLACEMENTS",title:"Placement reference sheet",text:"A downloadable snapshot of past placement companies and packages to help you benchmark and prepare.",links:[["Download sheet",pdf]],download:true},
{icon:<FaBook/>,tag:"NOTES",title:"MIS Student Dashboard",text:"A community-maintained Notion space collecting notes, links and academic references for the branch.",links:[["Open Notion","https://mis-notes.notion.site/Student-Dashboard-MIS-Branch-VIT-Vellore-325fa0bf8fe341cd82cfb9bd9dd15260"]],maker:"Pranit Modi"}
];
const Accessories=()=> <main className="page-shell resources-page"><header><span className="eyebrow">RESOURCE SHELF</span><h1 className="page-heading">Useful things, <span className="colourchangetext">kept close.</span></h1><p className="page-subtitle">A compact collection of tools, notes and references shared by the MIS community. Use what helps; ignore what doesn't.</p></header><section className="resource-grid">{items.map((x,i)=><article className="resource-card" key={x.title}><div className="resource-top"><span className="resource-icon">{x.icon}</span><small>{x.tag}</small></div><h2>{x.title}</h2><p>{x.text}</p><div className="resource-links">{x.links.map(([label,url])=>x.download?<a href={url} download key={label}>{label}<FaExternalLinkAlt/></a>:<a href={url} target="_blank" rel="noreferrer" key={label}>{label}<FaExternalLinkAlt/></a>)}</div>{x.maker&&<small className="maker">Shared by {x.maker}</small>}</article>)}</section></main>;
export default Accessories;
